name:                instant-compiler
version:             0.1.0.0

extra-source-files:
- README.md

description:         Please see the README

dependencies:
- base >= 4.7 && < 5
- array

ghc-options:
- -Wall
- -Wcompat
- -Widentities
- -Wincomplete-record-updates
- -Wincomplete-uni-patterns
- -Wmissing-home-modules
- -Wpartial-fields
- -Wredundant-constraints

library:
  source-dirs: src
  exposed-modules:
  - Lib.Utils
  - Grammar.AbsInstant
  - Grammar.LexInstant
  - Grammar.ParInstant
  when:
    - condition: false
      other-modules:
      - InstantLlvmCompiler
      - InstantJvmCompiler

executables:
  instant-llvm-compiler-exe:
    main:                InstantLlvmCompiler.hs
    source-dirs:         src
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - instant-compiler
    when:
      - condition: false
        other-modules:
          - InstantJvmCompiler
  instant-jvm-compiler-exe:
    main: InstantJvmCompiler.hs
    source-dirs: src
    ghc-options:
      - -threaded
      - -rtsopts
      - -with-rtsopts=-N
    dependencies:
      - instant-compiler
    when:
      - condition: false
        other-modules:
          - InstantLlvmCompiler
